In [ ]:
5*5

# Numpy Tutorial

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])

In [18]:
arr.size

4

In [19]:
arr.ndim

2

In [ ]:
arr.shape

In [12]:
arr=np.array([1,2,3,4]).reshape(2,-1)
arr

array([[1, 2],
       [3, 4]])

# reshape() function

In [17]:
arr1=np.array([1,2,3,4,5,6]).reshape(3,3)
arr1

ValueError: cannot reshape array of size 6 into shape (3,3)

In [16]:
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ones(), zeros(),diag(),eye()

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.diag(1,2,3)

TypeError: _diag_dispatcher() takes from 1 to 2 positional arguments but 3 were given

In [23]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

# randint() and rand() function

In [26]:
np.random.randint(1,101,10)

array([22, 37, 89, 85, 82, 60, 61, 33, 75, 27])

In [27]:
np.random.rand(5)

array([0.77289382, 0.34540839, 0.36751327, 0.16327397, 0.77662924])

In [28]:
np.random.randn(5)

array([ 0.76905694,  0.51032204,  0.78536907, -0.24573652, -0.10021583])

In [29]:
arr=np.random.randint(1,111,20).reshape(2,5)
arr

ValueError: cannot reshape array of size 20 into shape (2,5)

In [30]:
arr=np.random.randint(1,111,0).reshape(2,5)
arr

ValueError: cannot reshape array of size 0 into shape (2,5)

In [31]:
arr=np.random.randint(1,111,10).reshape(2,5)
arr

array([[ 28,   2,  81, 108,   5],
       [ 35,  51,  37,  21,  16]])

In [32]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

# <H1>linspace evenly spaced 5 no. </H1>

# indexing and slicing of numpy array

In [36]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [37]:
arr[2:]

array([3, 4, 5])

In [38]:
arr[2:4]

array([3, 4])

In [39]:
arr[-1:]

array([5])

In [40]:
arr[-3:]

array([3, 4, 5])

In [41]:
arr[0:5:2]

array([1, 3, 5])

In [42]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [43]:
sliced_array=arr[2:4] #view
sliced_array

array([3, 4])

In [44]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [45]:
arr

array([1, 2, 0, 0, 5])

In [46]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [47]:
sliced_array=arr[2:4].copy() #copy
sliced_array

array([3, 4])

In [48]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [49]:
arr

array([1, 2, 3, 4, 5])

In [51]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#first 1D array
matrix[0]

array([1, 2, 3])

In [53]:
#second element of first 1D array
matrix[0][1]

2

In [54]:
#using only single bracket # it is recommended
matrix[0,1]

2

In [55]:
matrix[:2, :2] #2D slicing

array([[1, 2],
       [4, 5]])

In [57]:
np.random.seed(123) #it allwos to generate same random numbers
arr=np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [58]:
arr[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

# conditional selectional

In [60]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# NumPy axis

### for rows put axis=1 and for coloumns put axis=0

In [66]:
arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[5, 8, 3],
       [5, 9, 1],
       [8, 4, 5]])

In [67]:
#calculate min element rowwise
np.min(arr,axis=1)

array([3, 1, 4])

In [68]:
#calculate max element coloumnwise
np.max(arr,axis=0)

array([8, 9, 5])

arr1=np.random.randint(1,10,9).reshape(3,3)
arr1

In [69]:
arr1=np.random.randint(1,10,9).reshape(3,3)
arr1

array([[7, 2, 6],
       [7, 3, 2],
       [9, 4, 6]])

In [70]:
arr2=np.random.randint(1,10,9).reshape(3,3)
arr2

array([[1, 3, 7],
       [3, 5, 5],
       [7, 4, 1]])

In [71]:
arr1+arr2

array([[ 8,  5, 13],
       [10,  8,  7],
       [16,  8,  7]])

In [72]:
arr1*arr2

array([[ 7,  6, 42],
       [21, 15, 10],
       [63, 16,  6]])

In [73]:
arr1.dot(arr2)

array([[55, 55, 65],
       [30, 44, 66],
       [63, 71, 89]])

# hstack() and vstack() function

##### these are used to concetenate two matrices horizontally and vertically

In [74]:
matrix1=np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[ 7,  5,  8],
       [ 7,  8,  2],
       [ 6,  8, 10]])

In [75]:
matrix2=np.random.randint(50,100,9).reshape(3,3)
matrix2

array([[70, 99, 62],
       [68, 67, 51],
       [94, 91, 98]])

In [77]:
out=np.vstack(matrix1,matrix2)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given