In [1]:
5*5

25

# Numpy Tutorial

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])

In [4]:
arr.size

4

In [5]:
arr.ndim

1

In [6]:
arr.shape

(4,)

In [7]:
arr=np.array([1,2,3,4]).reshape(2,-1)
arr

array([[1, 2],
       [3, 4]])

# reshape() function

In [12]:
arr1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ones(), zeros(),diag(),eye()

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.zeros(4)

array([0., 0., 0., 0.])

# randint() and rand() function

In [20]:
np.random.randint(1,101,10)

array([ 91,  86,  86,   8, 100,  71,  17,  19,  10,  70])

In [21]:
np.random.rand(5)

array([0.31743896, 0.24010142, 0.08233523, 0.43632324, 0.04411767])

In [22]:
np.random.randn(5)

array([-0.44614279, -0.64339805,  2.92540131, -2.00680848, -0.01359023])

In [24]:
arr=np.random.randint(1,111,10).reshape(2,5)
arr

array([[ 96,   2,   3,  49,  31],
       [ 11, 102,  21,  67,  58]])

In [25]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

# <H1>linspace evenly spaced 5 no. </H1>

# indexing and slicing of numpy array

In [26]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [27]:
arr[2:]

array([3, 4, 5])

In [28]:
arr[2:4]

array([3, 4])

In [29]:
arr[-1:]

array([5])

In [30]:
arr[-3:]

array([3, 4, 5])

In [31]:
arr[0:5:2]

array([1, 3, 5])

In [32]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [33]:
sliced_array=arr[2:4] #view
sliced_array

array([3, 4])

In [34]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [35]:
arr

array([1, 2, 0, 0, 5])

In [36]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [37]:
sliced_array=arr[2:4].copy() #copy
sliced_array

array([3, 4])

In [38]:
sliced_array[:]=0
sliced_array

array([0, 0])

In [39]:
arr

array([1, 2, 3, 4, 5])

In [40]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#first 1D array
matrix[0]

array([1, 2, 3])

In [42]:
#second element of first 1D array
matrix[0][1]

2

In [43]:
#using only single bracket # it is recommended
matrix[0,1]

2

In [44]:
matrix[:2, :2] #2D slicing

array([[1, 2],
       [4, 5]])

In [45]:
np.random.seed(123) #it allwos to generate same random numbers
arr=np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [46]:

arr[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

# conditional selectional

In [47]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:


arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [50]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# NumPy axis

### for rows put axis=1 and for coloumns put axis=0

In [52]:
arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[5, 8, 3],
       [5, 9, 1],
       [8, 4, 5]])

In [53]:
#calculate min element rowwise
np.min(arr,axis=1)

array([3, 1, 4])

In [54]:
#calculate max element coloumnwise
np.max(arr,axis=0)

array([8, 9, 5])

arr1=np.random.randint(1,10,9).reshape(3,3)
arr1

In [55]:
arr1=np.random.randint(1,10,9).reshape(3,3)
arr1

array([[7, 2, 6],
       [7, 3, 2],
       [9, 4, 6]])

In [56]:
arr2=np.random.randint(1,10,9).reshape(3,3)
arr2

array([[1, 3, 7],
       [3, 5, 5],
       [7, 4, 1]])

In [57]:
arr1+arr2

array([[ 8,  5, 13],
       [10,  8,  7],
       [16,  8,  7]])

In [58]:
arr1*arr2

array([[ 7,  6, 42],
       [21, 15, 10],
       [63, 16,  6]])

In [59]:
arr1.dot(arr2)

array([[55, 55, 65],
       [30, 44, 66],
       [63, 71, 89]])

# hstack() and vstack() function

##### these are used to concetenate two matrices horizontally and vertically

In [61]:
matrix2=np.random.randint(50,100,9).reshape(3,3)
matrix2

array([[70, 99, 62],
       [68, 67, 51],
       [94, 91, 98]])