# Numpy Exercise

### import numpy library

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])

In [4]:
arr1=np.arange(20,41)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [5]:
arr2=np.ones(10)*5
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
arr3=np.random.randint(1,10,8).reshape(2,2,2)
arr3

array([[[1, 9],
        [7, 8]],

       [[2, 6],
        [4, 8]]])

In [10]:
arr4=np.random.rand(25).reshape(5,5)
arr4

array([[0.73103425, 0.40440352, 0.83200627, 0.44889159, 0.79499151],
       [0.13565308, 0.90156175, 0.68755813, 0.28864229, 0.27700616],
       [0.74592247, 0.1493774 , 0.48810865, 0.24209325, 0.20107521],
       [0.47800548, 0.20490927, 0.80064538, 0.10717246, 0.58054213],
       [0.9055725 , 0.59859453, 0.58250475, 0.03968633, 0.95052849]])

In [15]:
np.random.seed(123)
arr5=np.random.randint(1,50,20)
arr5[arr5%2 == 0]=-1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

In [16]:
arr6=np.array([1,2,3,4,5])
arr7=np.array([6,7,8,9,10])
np.hstack((arr6,arr7))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])